#!/usr/bin/env bash

git config --global core.excludesfile ~/.gitignore
# install homebrew
if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

brew install \
    bat \
    ccat \
    direnv \
    duti \
    exa \
    fd \
    fish \
    git \
    gpg \
    htop \
    jq \
    pipx \
    pyenv \
    ripgrep \
    shellcheck \
    snappy \
    the_silver_searcher \
    tldr \
    wget \
    youtube-dl
duti ~/.duti