#!/usr/bin/env bash

git config --global core.excludesfile ~/.gitignore
# install homebrew
if ! hash brew  &> /dev/null
then
    echo | /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

brew install \
    bat \
    ccat \
    direnv \
    duti \
    exa \
    fd \
    fish \
    git \
    gpg \
    htop \
    jq \
    pipx \
    pyenv \
    ripgrep \
    shellcheck \
    snappy \
    the_silver_searcher \
    tldr \
    wget \
    youtube-dl
duti ~/.duti