alias gl 'git lg'
alias .. 'cd ..'
alias co 'git checkout'
alias gb 'git checkout -'
alias gc 'git commit -v'
alias gca 'git commit -v --amend'
alias gp 'git pull --rebase --prune'
alias cat 'ccat'
alias dns_flush 'sudo killall -HUP mDNSResponder'
alias flush_dns dns_flush
